services:
  freeswitch:
    image: ghcr.io/mohan-cao/freeswitch-docker-compose:nightly
    container_name: freeswitch
    hostname: freeswitch
    restart: always
    volumes:
      - ./freeswitch/conf:/etc/freeswitch
      - ./logs:/usr/local/freeswitch/log
    network_mode: host
    privileged: true

